#系统配置
system:
  host: "0.0.0.0"
  port: 8080
  env: debug
  # env: relase

#logger 日志配置
logger:
  level: info
  prefix: "Blog"
  director: logger
  showline: true
  log_in_console: true

#mysql配置
mysql:
  host: 127.0.0.1
  port: 3306
  db: blog
  username: root
  password: 123456
  log_level: dev
  charset: utf8
  maxIdle: 50
  maxOpen: 150

#redis配置
redis:
  address: 127.0.0.1:6379
  password:
  db: 0